### ISSUE TITLE
Please state license to allow for distribution

### ISSUE THREAD

**Issue by petercolberg** [hlandau/buildinfo#1]
The source code in this repository is missing a declaration of the license, which prevents it from being distributed as a dependency of acmetool ≥ 0.0.55. Could you state the license in `README.md`, e.g., in the same manner as for [easyconfig](https://github.com/hlandau/easyconfig/blob/master/README.md#licence), in order to allow distribution of acmetool ≥ 0.0.55 with its dependencies?

**Comment by hlandau** [comment]
Licence tracking information is tracked via [RILTS](https://github.com/hlandau/rilts/blob/master/RILTS.md).
